(function(){
var d=null;function f(a){if(a!=d)return escape(a.toString());return""}function h(a){if(a!=d)return a.toString().substring(0,256);return""}function i(a,b){var e=f(b);if(e!=""){var c=f(a);if(c!="")return"&".concat(c,"=",e)}return""}function j(a){if(a!=d){var b=a.toString();if(2==b.length)return i("hl",b);if(5==b.length)return i("hl",b.substring(0,2))+i("gl",b.substring(3,5))}return""}
function k(a,b,e){var c=[];if(a){var g=a.screen;if(g){c.push(i("u_h",g.height));c.push(i("u_w",g.width));c.push(i("u_ah",g.availHeight));c.push(i("u_aw",g.availWidth));c.push(i("u_cd",g.colorDepth))}a.history&&c.push(i("u_his",a.history.length))}e&&typeof e.getTimezoneOffset=="function"&&c.push(i("u_tz",-e.getTimezoneOffset()));if(b){typeof b.javaEnabled=="function"&&c.push(i("u_java",b.javaEnabled()));b.plugins&&c.push(i("u_nplug",b.plugins.length));b.mimeTypes&&c.push(i("u_nmime",b.mimeTypes.length))}return c.join("")}
function l(a,b){var e="";if(b){var c=b.referrer;if(a&&a.top&&b.location&&a.top.location==b.location){e+=i("ref",h(c));c=b.location}e+=i("url",h(c))}return e}function m(a){if(a&&a.location&&a.location.protocol&&a.location.protocol.toString().toLowerCase()=="https:")return"https:";return"http:"}
function n(a,b,e){var c="/?";if(a.google_conversion_type=="landing")c="/extclk?";var g=m(a)+"//www.googleadservices.com/pagead/conversion/"+f(a.google_conversion_id)+c+"random="+f(a.google_conversion_time);g+=[i("cv",a.google_conversion_js_version),i("fst",a.google_conversion_first_time),i("num",a.google_conversion_snippets),i("fmt",a.google_conversion_format),i("value",a.google_conversion_value),i("label",a.google_conversion_label),i("bg",a.google_conversion_color),j(a.google_conversion_language),
i("guid","ON"),k(a,b,a.google_conversion_date),l(a,e)].join("");return g}function o(a){var b={ar:1,bg:1,cs:1,da:1,de:1,el:1,en_AU:1,en_US:1,en_GB:1,es:1,et:1,fi:1,fr:1,hi:1,hr:1,hu:1,id:1,is:1,it:1,iw:1,ja:1,ko:1,lt:1,nl:1,no:1,pl:1,pt_BR:1,pt_PT:1,ro:1,ru:1,sk:1,sl:1,sr:1,sv:1,th:1,tl:1,tr:1,vi:1,zh_CN:1,zh_TW:1};if(b[a])return a+".html";return"en_US.html"}
function p(a,b,e){var c=n(a,b,e),g=function(q,r,s){return'<img height="'+s+'" width="'+r+'" border="0" src="'+q+'" />'};if(a.google_conversion_format==0){var t=m(a)+"//services.google.com/sitestats/"+o(a.google_conversion_language)+"?cid="+f(a.google_conversion_id);return'<a href="'+t+'" target="_blank">'+g(c,135,27)+"</a>"}else return a.google_conversion_snippets>1||a.google_conversion_format==3?g(c,1,1):'<iframe name="google_conversion_frame" width="'+(a.google_conversion_format==2?200:300)+'" height="'+
(a.google_conversion_format==2?26:13)+'" src="'+c+'" frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no">'+g(c.replace(/\?random=/,"?frame=0&random="),1,1)+"</iframe>"}
function u(a){if(a.google_conversion_type=="landing"||!a.google_conversion_id)return false;a.google_conversion_date=new Date;a.google_conversion_time=a.google_conversion_date.getTime();if(typeof a.google_conversion_snippets=="number"&&a.google_conversion_snippets>0)a.google_conversion_snippets+=1;else a.google_conversion_snippets=1;if(typeof a.google_conversion_first_time!="number")a.google_conversion_first_time=a.google_conversion_time;a.google_conversion_js_version="6";if(a.google_conversion_format!=
0&&a.google_conversion_format!=1&&a.google_conversion_format!=2&&a.google_conversion_format!=3)a.google_conversion_format=1;return true}function v(a){a.google_conversion_date=d;a.google_conversion_time=d;a.google_conversion_js_version=d;a.google_conversion_id=d;a.google_conversion_value=d;a.google_conversion_label=d;a.google_conversion_language=d;a.google_conversion_format=d;a.google_conversion_color=d;a.google_conversion_type=d}
function w(a,b){var e="[\\?&;]"+b,c=new RegExp(e);return c.exec(a)!=d}function x(){var a=document.getElementsByTagName("head")[0];if(!a){a=document.createElement("head");document.getElementsByTagName("html")[0].insertBefore(a,document.getElementsByTagName("body")[0])}var b=document.createElement("script");b.src="conversion_debug_overlay.js";a.appendChild(b)};function y(a,b,e){if(a)if(w(document.URL,"google_debug"))x();else{try{u(a)&&e.write(p(a,b,e))}catch(c){}v(a)}}y(window,navigator,document);
})()
